### ISSUE TITLE
Checkout issue due to large filename

### ISSUE THREAD

**Issue by adamculp** [szabgab/codeandtalk.com#170]
When cloning the repo I receive the following error:

error: unable to create file data/videos/rubyconf-taiwan-2015/rubyconf-day1-r2-04-jian-wei-hang-gulp-on-rails-return-front-end-back-to-front-end-developers-huan-gei-qian-duan-gong-cheng-shi-yi-ge-tian-kong.json (File name too long)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by szabgab** [comment]
Thanks for reporting.
What OS ? Do you use git on the command line? Which version?

**Comment by adamculp** [comment]
I am on Ubuntu 16.04 (my laptop). Tried using JetBrains IDE, and then also tried via CLI. Both fail with the same message.

**Comment by szabgab** [comment]
Strange. It works for me on both OSX and Linux. Just checked on an Ubuntu 16.04.
What kind of filesystem do you use?

This is what I just tried:

```
$ lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL
NAME   FSTYPE SIZE MOUNTPOINT LABEL
vda            20G
└─vda1 ext4    20G /          cloudimg-rootfs
```
git version 2.7.4

Could you paste the git command you are using on the command line?

**Comment by adamculp** [comment]
Yes, very strange. Wonder if it is causing issue with the Ubuntu encrypted home directory. (would be a first)

Filesystem:

```
$ lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL
NAME                    FSTYPE        SIZE MOUNTPOINT LABEL
sda                                 931.5G            
├─sda1                  ext2          487M /boot      
├─sda2                                  1K            
└─sda5                  crypto_LUKS   931G            
  └─sda5_crypt          LVM2_member   931G            
    ├─ubuntu--vg-root   ext4        915.1G /          
    └─ubuntu--vg-swap_1 swap         15.9G            
      └─cryptswap1      swap         15.9G [SWAP]     
sr0                                  1024M
```
Git command:
```
$ git clone https://github.com/szabgab/codeandtalk.com.git codeandtalk
```

**Comment by adamculp** [comment]
Verified: Was able to do the clone outside of the encrypted home directory.

**Comment by szabgab** [comment]
Great. So does this work for you for now?

In any case I'll shorten the file names. These were automatically generated by the code that fetches the playlists from YouTube.

**Comment by adamculp** [comment]
Should be OK for now. I just wanted to add a couple events, speaker, and talks. Since I didn't see a form I assumed a PR was the way to add those.

**Comment by szabgab** [comment]
That would be great.
I should probably make that more obvious on the web site.

**Comment by szabgab** [comment]
BTW This, or something related might be the issue: http://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs The problematic filename is 149 bytes long and the recommended limit for this encrypted filesystem is 140 characters.
