### ISSUE TITLE
Sort the event in the series

### ISSUE THREAD

**Issue by rollandf** [szabgab/codeandtalk.com#225]
The events in the series pages are not sorted.
For example :
 Apache Conference

    ApacheCon North America 2013
    ApacheCon North America 2014
    ApacheCon North America 2015
    ApacheCon Europe 2015
    ApacheCon North America 2016
    ApacheCon Europe
    ApacheCon North America 2017

**Comment by szabgab** [comment]
I think I've fixed that. Please check.

**Comment by rollandf** [comment]
👍  Looks great. Thanks.
