### ISSUE TITLE
add events: https://www.devopsdays.org/

### ISSUE THREAD

**Issue by szabgab** [szabgab/codeandtalk.com#413]
https://github.com/szabgab/codeandtalk.com/blob/main/docs/EVENTS.md

**Comment by yeshijinsel** [comment]
so we just create an event by ourself 
NO data about that

**Comment by szabgab** [comment]
@yeshijinsel   I did not understand your comment.

**Comment by yeshijinsel** [comment]
i try on this issue

**Comment by yeshijinsel** [comment]
i will do this

**Comment by szabgab** [comment]
Some DevOpsdays events were already added.
