### ISSUE TITLE
add event: http://www.opencamps.org/2017

### ISSUE THREAD

**Issue by szabgab** [szabgab/codeandtalk.com#414]
https://twitter.com/opencamps
see https://github.com/szabgab/codeandtalk.com/blob/main/docs/EVENTS.md

**Comment by lewjuh** [comment]
PR opened! Hope its okay.

**Comment by lewjuh** [comment]
Can do some more, just wanted to check it was all okay first.

**Comment by szabgab** [comment]
Sure. There are plenty in #422
