### ISSUE TITLE
Event" GraphQL Summit" A11y has incorrect link (404)

### ISSUE THREAD

**Issue by constructor-igor** [szabgab/codeandtalk.com#437]
![image](https://user-images.githubusercontent.com/1849690/31866659-9848142a-b78b-11e7-8aef-c5624484304b.png)

page https://codeandtalk.com/2017-08-01 shows error 404

![image](https://user-images.githubusercontent.com/1849690/31866671-acc4b502-b78b-11e7-8b88-cfb5c95a3e30.png)

**Comment by szabgab** [comment]
And where did find that link?

**Comment by constructor-igor** [comment]
![image](https://user-images.githubusercontent.com/1849690/31874254-e4c32372-b7d0-11e7-8ac3-6613ad8eb8d5.png)

**Comment by szabgab** [comment]
Thanks, but it would be easier if you pasted the URL pf the page where you found that broken link.

**Comment by constructor-igor** [comment]
ok, https://codeandtalk.com/conferences

**Comment by szabgab** [comment]
Thanks. Apparently there was an invalid value in the `accessibility` field int the JSON file describing that event. ed8f3251 fixes it.

Thanks for reporting.
