### ISSUE TITLE
Fix page layouts

### ISSUE THREAD

**Issue by pauljacobson** [szabgab/codeandtalk.com#489]
The static pages have an inconsistent layout. The [About Code And Talk](https://codeandtalk.com/about) page, for example, lacks the padding a page like the [Contribute to Code And Talk](https://codeandtalk.com/contribute) has. The relevant styling components need to be made site-wide.

![screen shot 2017-12-16 at 13 26 36](https://user-images.githubusercontent.com/2912202/34069992-0e3d6316-e265-11e7-824a-9cfc0fe703b7.png)

I'm happy to take this on.

**Comment by szabgab** [comment]
go for it.

**Comment by pauljacobson** [comment]
Ok, I've submitted a pull request with the basic page layout changes. I have some other changes to make to page content but I'll wait for you to finish reviewing these pull requests before moving on to those changes.

**Comment by szabgab** [comment]
Is this done? Can we close this issue or is there more to be done here?

**Comment by pauljacobson** [comment]
I believe this work is complete. I can do the other layout and CSS edits separately.

**Comment by szabgab** [comment]
Thanks
