### ISSUE TITLE
Extend error checking beyond one error

### ISSUE THREAD

**Issue by MLRiain** [szabgab/codeandtalk.com#533]
The error checking apparently stops when it finds one error and does not go through the rest of the file. So if a person has made multiple errors, as I have on occasion, it reports only the first. The next time, it reports the second, and so on. It would be much more efficient if it would test the entire file and report all errors at once.

**Comment by szabgab** [comment]
It has been implemented to many error messages. Please report any case where one error was hiding another error. Please also report cases when Travis fails without any ERROR entry.
