### ISSUE TITLE
Readme: upstream command, minor mistake?

### ISSUE THREAD

**Issue by Phhofm** [szabgab/codeandtalk.com#569]
In Readme, section "Process with command line Git client", there might be a minor mistake in the 'add upstream' command.
If I use the described "git remote add upstream https://github.com/szabgab/codeandtalk.git" command, and then do a "git fetch upstream", it throws a "fatal: repository 'https://github.com/szabgab/codeandtalk.git/' not found"
Should it be "git remote add upstream https://github.com/szabgab/codeandtalk.com.git" instead? (this works)

Please forgive me if this is not an issue, I am very new to contributing to projects.
If this is an issue, I will gladly make the minor correction and make a pull request as exercise.
Thanks

**Comment by szabgab** [comment]
You are right. Thank you for pointing it out. Please send a fix. (BTW are you on the Hacktoberfest? if not yet do it before you send the PR)

**Comment by Phhofm** [comment]
Thank you for your reply :) Yes, I saw the Hacktoberfest and that is what actually got me started yesterday evening and led me here ;)

**Comment by szabgab** [comment]
https://github.com/szabgab/codeandtalk.com/commit/d45a31297a44e92652594a00317c06e872531cce
